// <auto-generated />
using System;
using GameClubManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameClubManager.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250430000000_AddAdminNotificationsTable")]
    partial class AddAdminNotificationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameClubManager.Shared.Models.AdminNotification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int?>("ComputerId")
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit");

                b.Property<string>("Message")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int?>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ComputerId");

                b.HasIndex("UserId");

                b.ToTable("AdminNotifications");
            });

            // Отношения между таблицами
            modelBuilder.Entity("GameClubManager.Shared.Models.AdminNotification", b =>
            {
                b.HasOne("GameClubManager.Shared.Models.Computer", null)
                    .WithMany()
                    .HasForeignKey("ComputerId");

                b.HasOne("GameClubManager.Shared.Models.User", null)
                    .WithMany()
                    .HasForeignKey("UserId");
            });
        }
    }
} 