// <auto-generated />
using System;
using GameClubManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameClubManager.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501000000_AddCategoryAndImageUrlToFoodItems")]
    partial class AddCategoryAndImageUrlToFoodItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            
            // Пропустим полное определение модели, так как она уже определена в последнем снимке
            
#pragma warning restore 612, 618
        }
    }
} 